# Generated by Django 3.0.6 on 2020-09-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openpairsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='brush',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='clean_room',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='shower',
        ),
    ]
